version: '2'
services:

  dsparseyapi:
    build: docker/dsparseyapi
    command: /work/serving/parsey_api --port=9000 /work/api/parsey_model
    volumes:
      - .:/root
    ports:
      - "9000:9000"
    #environment:
   #   - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    depends_on:
      - db
      # - cache
      # - broker
      # - workers
    links:
      - db
      # - cache
      # - broker
      # - workers
    env_file:
          - docker/base.env
  db:
    build: docker/postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - docker/base.env
    volumes:
      - ".dbcache:/var/lib/postgresql/data"

